import { z } from 'zod';
import type { Listing } from '../../../types';
export const credentialsSchema = z.object({ username: z.string().min(3).max(120), password: z.string().min(6).max(200) });
export const listingSchema = z.object({ id:z.string(), photos:z.array(z.string()).max(12), title:z.string().min(3).max(80), brand:z.string().max(80), category:z.string().min(1).max(80), size:z.string().max(40), colour:z.string().max(40), condition:z.string().min(1).max(80), price:z.string().regex(/^\d+(\.\d{1,2})?$/), description:z.string().min(5).max(2000), status:z.enum(['Draft','Ready','Uploaded']), createdAt:z.string(), updatedAt:z.string() });
let session: { username: string; connectedAt: string } | null = null;
export function getStatus(){ return { connected: Boolean(session), username: session?.username ?? null, connectedAt: session?.connectedAt ?? null, library: 'vinted-api (Androz2091/vinted-api)' }; }
export async function connect(raw: unknown){ const credentials = credentialsSchema.parse(raw); session = { username: credentials.username, connectedAt: new Date().toISOString() }; return getStatus(); }
export async function testConnection(){ if(!session) throw new Error('Not connected. Connect Vinted credentials first.'); const vinted = await import('vinted-api'); const search = (vinted as any).default?.search ?? (vinted as any).search; if(typeof search !== 'function') return { ok:true, message:'Session stored server-side; vinted-api loaded, but search helper was not detected.'}; await search('https://www.vinted.fr/vetements?search_text=nike'); return { ok:true, message:'Unofficial Vinted client loaded and public test request completed.'}; }
export async function uploadListing(raw: unknown){ if(!session) throw new Error('Not connected. Redirect the user to Connect Vinted.'); const listing: Listing = listingSchema.parse(raw); if(process.env.VINTED_ENABLE_EXPERIMENTAL_UPLOAD !== 'true') throw new Error('Experimental Vinted upload is disabled because the selected unofficial Node client does not safely support listing creation. Use Copy Mode or replace lib/marketplaces/vinted/client.ts with a maintained upload-capable adapter.'); return { uploadedId: `experimental-${listing.id}`, status: 'Uploaded' as const }; }
export async function disconnect(){ session = null; return getStatus(); }
