'use client';
import { useEffect, useMemo, useState } from 'react';
import { emptyListing, Listing } from '@/lib/types';
import { loadListings, saveListings } from '@/lib/storage';
import { reviseListing } from '@/lib/aiRevision';

const nav = ['Overview','Create','Inventory','Ratings','Messages','Connect Vinted'];
const vintedLoginUrl = 'https://www.vinted.es/member/signup/select_type?ref_url=%2F';

export default function AppShell(){
  const [tab,setTab]=useState('Overview');
  const [listings,setListings]=useState<Listing[]>([]);
  const [draft,setDraft]=useState<Listing>(emptyListing());
  const [status,setStatus]=useState<any>({connected:false});
  const [remote,setRemote]=useState<Record<string, any>>({});
  const [msg,setMsg]=useState('');
  const ai=useMemo(()=>reviseListing(draft),[draft]);
  useEffect(()=>{setListings(loadListings()); refreshStatus();},[]);
  const refreshStatus=()=>fetch('/api/vinted/status').then(r=>r.json()).then(setStatus);
  const persist=(x:Listing[])=>{setListings(x);saveListings(x)};
  const up=(k:keyof Listing,v:any)=>setDraft({...draft,[k]:v,updatedAt:new Date().toISOString()});
  const save=()=>{const item={...draft,status:'Ready' as const,updatedAt:new Date().toISOString()}; persist([item,...listings.filter(l=>l.id!==item.id)]); setDraft(emptyListing()); setTab('Inventory')};
  async function upload(l:Listing){ setMsg('Uploading through backend-only Vinted adapter…'); const r=await fetch('/api/vinted/upload-listing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(l)}); const j=await r.json(); if(!r.ok){setMsg(j.error); persist(listings.map(x=>x.id===l.id?{...x,status:'Draft'}:x)); return;} persist(listings.map(x=>x.id===l.id?{...x,status:'Uploaded'}:x)); setMsg(`Uploaded: ${j.uploadedId}`)}
  async function loadRemote(kind:string,url:string){ setMsg(`Loading ${kind}…`); const r=await fetch(url); const j=await r.json(); setRemote(x=>({...x,[kind]:j})); setMsg(r.ok?'Loaded.':j.error); }
  return <div className="min-h-screen bg-[#070816] text-white"><div className="fixed inset-0 bg-[radial-gradient(circle_at_20%_10%,rgba(124,58,237,.45),transparent_30rem),radial-gradient(circle_at_80%_20%,rgba(6,182,212,.35),transparent_28rem),linear-gradient(135deg,#070816,#111827_50%,#020617)]"/><aside className="glass fixed left-6 top-6 bottom-6 z-10 hidden w-72 flex-col rounded-[2rem] p-5 md:flex"><h1 className="text-3xl font-black">AutoVinted AI</h1><p className="mt-2 text-sm text-slate-300">Dark dashboard for real Vinted sessions.</p><ProfileBadge status={status}/><nav className="mt-6 grid gap-2">{nav.map(n=><button key={n} onClick={()=>setTab(n)} className={`rounded-2xl px-4 py-3 text-left font-semibold ${tab===n?'bg-white text-black':'bg-white/10 text-white hover:bg-white/20'}`}>{n}</button>)}</nav><Footer/></aside><main className="relative z-0 mx-auto max-w-7xl p-4 pb-28 md:ml-80 md:p-8"><header className="glass mb-5 rounded-[2rem] p-5 md:hidden"><h1 className="text-2xl font-black">AutoVinted AI</h1><ProfileBadge status={status}/></header>{msg&&<div className="glass mb-4 rounded-2xl p-3 text-sm text-cyan-100">{msg}</div>}{tab==='Overview'&&<Overview listings={listings} status={status} loadRemote={loadRemote} remote={remote}/>} {tab==='Create'&&<Create draft={draft} up={up} ai={ai} applyAi={()=>setDraft({...draft,title:ai.title,description:ai.description,category:ai.category,condition:ai.condition})} save={save}/>} {tab==='Inventory'&&<Inventory listings={listings} persist={persist} edit={(l:Listing)=>{setDraft(l);setTab('Create')}} upload={(l:Listing)=>status.connected?upload(l):setTab('Connect Vinted')} msg={msg}/>} {tab==='Ratings'&&<RemotePage title="Ratings & reviews" data={remote.ratings} load={()=>loadRemote('ratings','/api/vinted/ratings')}/>} {tab==='Messages'&&<Messages data={remote.messages} load={()=>loadRemote('messages','/api/vinted/messages')}/>} {tab==='Connect Vinted'&&<Connect status={status} refresh={refreshStatus}/>}<div className="mt-8 md:hidden"><Footer/></div></main><nav className="safe-bottom glass fixed bottom-3 left-3 right-3 z-20 grid grid-cols-6 rounded-3xl p-1 md:hidden">{nav.map(n=><button className={`rounded-2xl p-2 text-[10px] font-bold ${tab===n?'bg-white text-black':'text-white'}`} onClick={()=>setTab(n)} key={n}>{n.replace(' Vinted','')}</button>)}</nav></div>}
function Footer(){return <footer className="mt-auto pt-6 text-center text-xs font-semibold text-slate-300">Prompt by Marc</footer>}
function ProfileBadge({status}:any){return <div className="mt-4 flex items-center gap-3 rounded-2xl bg-white/10 p-3">{status.avatar?<img src={status.avatar} alt="Vinted avatar" className="h-10 w-10 rounded-full object-cover"/>:<div className="h-10 w-10 rounded-full bg-gradient-to-br from-cyan-400 to-fuchsia-500"/>}<div><p className="text-xs text-slate-300">{status.connected?'Connected':'Not connected'}</p><b>{status.username||'Vinted session'}</b></div></div>}
function Card({children}:any){return <div className="glass rounded-[2rem] p-5">{children}</div>}
function Overview({listings,status,loadRemote,remote}:any){return <section className="grid gap-5 lg:grid-cols-3"><Card><h2 className="text-3xl font-black">Overview</h2><p className="mt-2 text-slate-300">Local drafts: {listings.length}</p><p className="text-slate-300">Ready: {listings.filter((l:Listing)=>l.status==='Ready').length}</p><p className="text-slate-300">Uploaded: {listings.filter((l:Listing)=>l.status==='Uploaded').length}</p></Card><Card><h3 className="text-xl font-black">My Vinted profile</h3><button onClick={()=>loadRemote('profile','/api/vinted/profile')} className="mt-4 rounded-2xl bg-white px-4 py-3 font-bold text-black">Load profile</button><Json data={remote.profile||status}/></Card><Card><h3 className="text-xl font-black">My products</h3><button onClick={()=>loadRemote('products','/api/vinted/products')} className="mt-4 rounded-2xl bg-cyan-400 px-4 py-3 font-bold text-black">Load products</button><Json data={remote.products}/><a href="https://www.vinted.es/member/items" target="_blank" className="mt-3 inline-block text-cyan-200">Open in Vinted</a></Card></section>}
function Create({draft,up,ai,applyAi,save}:any){return <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card><h2 className="text-3xl font-black">Create Listing</h2><input type="file" accept="image/*" capture="environment" multiple className="mt-4 w-full rounded-2xl bg-white/10 p-3" onChange={async e=>{const files=[...(e.target.files||[])]; const photos=await Promise.all(files.map(f=>new Promise<string>(res=>{const r=new FileReader(); r.onload=()=>res(String(r.result)); r.readAsDataURL(f)}))); up('photos',photos)}}/><div className="mt-4 grid gap-3 sm:grid-cols-2">{(['title','brand','category','size','colour','condition','price'] as (keyof Listing)[]).map(f=><input key={f} value={String(draft[f]||'')} onChange={e=>up(f,e.target.value)} placeholder={f} className="rounded-2xl bg-white/10 p-3 outline-none placeholder:text-slate-400"/>)}<textarea value={draft.description} onChange={e=>up('description',e.target.value)} placeholder="Description" className="min-h-32 rounded-2xl bg-white/10 p-3 outline-none placeholder:text-slate-400 sm:col-span-2"/></div><div className="mt-4 flex flex-wrap gap-3"><button onClick={applyAi} className="rounded-2xl bg-fuchsia-500 px-5 py-3 font-bold">AI Revision</button><button onClick={save} className="rounded-2xl bg-white px-5 py-3 font-bold text-black">Save Ready Draft</button></div></Card><Preview listing={draft} ai={ai}/></section>}
function Preview({listing,ai}:any){return <Card><h3 className="text-xl font-black">Vinted-style Preview</h3><div className="mt-4 overflow-hidden rounded-3xl bg-white text-black"><div className="aspect-square bg-slate-100">{listing.photos?.[0]&&<img src={listing.photos[0]} alt="Listing preview" className="h-full w-full object-cover"/>}</div><div className="p-4"><b>{listing.title||ai.title||'Your polished title'}</b><p className="text-sm text-slate-500">{listing.brand} · {listing.size} · {listing.condition}</p><p className="mt-2 text-2xl font-black">{listing.price?'£'+listing.price:ai.priceRange}</p><p className="mt-3 whitespace-pre-wrap text-sm">{listing.description||ai.description}</p><p className="mt-3 text-xs text-indigo-700">Keywords: {ai.keywords.join(', ')}</p></div></div></Card>}
function Inventory({listings,persist,edit,upload}:any){return <section><h2 className="mb-5 text-3xl font-black">Product cards</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{listings.map((l:Listing)=><Card key={l.id}><b>{l.title}</b><p className="text-slate-300">{l.status} · £{l.price}</p>{l.photos[0]&&<img src={l.photos[0]} alt="Product" className="mt-3 aspect-square rounded-2xl object-cover"/>}<div className="mt-3 flex flex-wrap gap-2">{['Copy title','Copy description','Copy price'].map(x=><button className="rounded-xl bg-white/10 px-3 py-2 text-xs" onClick={()=>navigator.clipboard.writeText(x.includes('title')?l.title:x.includes('price')?l.price:l.description)} key={x}>{x}</button>)}<button onClick={()=>navigator.clipboard.writeText(JSON.stringify(l,null,2))} className="rounded-xl bg-white/10 px-3 py-2 text-xs">Copy all</button><a href="https://www.vinted.es/items/new" target="_blank" className="rounded-xl bg-white/10 px-3 py-2 text-xs">Open Vinted</a><button onClick={()=>edit(l)} className="rounded-xl bg-blue-500 px-3 py-2 text-xs">Edit</button><button onClick={()=>persist([{...l,id:crypto.randomUUID(),status:'Draft'},...listings])} className="rounded-xl bg-purple-500 px-3 py-2 text-xs">Duplicate</button><button onClick={()=>upload(l)} className="rounded-xl bg-cyan-400 px-3 py-2 text-xs text-black">Upload to Vinted</button><button onClick={()=>persist(listings.filter((x:Listing)=>x.id!==l.id))} className="rounded-xl bg-red-500 px-3 py-2 text-xs">Delete</button></div></Card>)}</div></section>}
function Connect({status,refresh}:any){const [cookie,setCookie]=useState(''); const [msg,setMsg]=useState(''); const call=async(url:string,body?:any)=>{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}); const j=await r.json(); setMsg(j.error||j.message||'Done'); refresh(); if(r.ok) setCookie('');};return <Card><h2 className="text-3xl font-black">Connect Vinted</h2><p className="mt-3 text-slate-300">Vinted has no public OAuth for this app. Continue with Vinted opens the real Vinted sign-in page; then paste your session cookie here so it is sent only to backend API routes.</p><a href={vintedLoginUrl} target="_blank" className="mt-5 inline-block rounded-2xl bg-gradient-to-r from-cyan-300 to-fuchsia-400 px-5 py-3 font-black text-black">Continue with Vinted</a><textarea value={cookie} onChange={e=>setCookie(e.target.value)} placeholder="Paste Vinted session cookie here. It is not stored in LocalStorage." className="mt-5 min-h-28 w-full rounded-2xl bg-white/10 p-3 outline-none placeholder:text-slate-400"/><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>call('/api/vinted/connect-session',{cookie})} className="rounded-2xl bg-white px-5 py-3 font-bold text-black">Connect session</button><button onClick={()=>call('/api/vinted/test')} className="rounded-2xl bg-cyan-400 px-5 py-3 font-bold text-black">Test Connection</button><button onClick={()=>call('/api/vinted/disconnect')} className="rounded-2xl bg-white/10 px-5 py-3 font-bold">Disconnect</button></div><ProfileBadge status={status}/>{msg&&<p className="mt-4 text-sm text-cyan-100">{msg}</p>}</Card>}
function RemotePage({title,data,load}:any){return <Card><h2 className="text-3xl font-black">{title}</h2><button onClick={load} className="mt-4 rounded-2xl bg-white px-4 py-3 font-bold text-black">Load from Vinted</button><Json data={data}/><a href="https://www.vinted.es/member" target="_blank" className="mt-3 inline-block text-cyan-200">Open in Vinted</a></Card>}
function Messages({data,load}:any){return <Card><h2 className="text-3xl font-black">Messages</h2><button onClick={load} className="mt-4 rounded-2xl bg-white px-4 py-3 font-bold text-black">Load messages</button><p className="mt-3 text-sm text-slate-300">Replies are attempted only if the backend adapter supports them; otherwise the exact backend error is shown and Vinted is opened manually.</p><Json data={data}/><a href="https://www.vinted.es/inbox" target="_blank" className="mt-3 inline-block text-cyan-200">Open messages in Vinted</a></Card>}
function Json({data}:any){return data?<pre className="mt-4 max-h-96 overflow-auto rounded-2xl bg-black/40 p-3 text-xs text-cyan-100">{JSON.stringify(data,null,2)}</pre>:<p className="mt-4 text-sm text-slate-400">No data loaded. Real Vinted responses or exact backend errors will appear here.</p>}
